In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("06~23 광주아파트(매매).csv", encoding="EUC-KR")
data

C:\Users\gjaischool1\AppData\Local\Temp\ipykernel_2176\1910380689.py:1: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("06~23 광주아파트(매매).csv", encoding="EUC-KR")

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,광주광역시 광산구 도산동,1138-2,1138,2,대덕1,59.3100,202303,18,"9,800",4,1990,송도로 143,NaN,중개거래,광주 광산구
1,광주광역시 광산구 도산동,790,790,0,대주피오레1차,84.9800,202302,7,"21,000",2,2000,송도로182번길 55,NaN,중개거래,광주 광산구
2,광주광역시 광산구 도산동,790,790,0,대주피오레1차,84.9800,202305,31,"22,350",5,2000,송도로182번길 55,NaN,중개거래,광주 광산구
3,광주광역시 광산구 도산동,820,820,0,대주피오레2차,84.7575,202305,9,"22,400",5,2001,송도로182번길 16-3,NaN,직거래,-
4,광주광역시 광산구 도산동,820,820,0,대주피오레2차,84.7575,202305,13,"22,000",13,2001,송도로182번길 16-3,NaN,중개거래,광주 광산구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425074,광주광역시 서구 화정동,440,440,0,화정우미,115.1850,200611,10,"19,000",17,1996,염화로31번길 23,NaN,NaN,NaN
425075,광주광역시 서구 화정동,440,440,0,화정우미,84.8300,200611,27,"12,000",6,1996,염화로31번길 23,NaN,NaN,NaN
425076,광주광역시 서구 화정동,440,440,0,화정우미,59.8300,200611,30,"7,700",2,1996,염화로31번길 23,NaN,NaN,NaN
425077,광주광역시 서구 화정동,440,440,0,화정우미,84.8400,200612,6,"12,170",16,1996,염화로31번길 23,NaN,NaN,NaN
425078,광주광역시 서구 화정동,440,440,0,화정우미,115.1850,200612,12,"17,500",14,1996,염화로31번길 23,NaN,NaN,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 425079 entries, 0 to 425078
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   시군구       425079 non-null  object
 1   번지        425079 non-null  object
 2   본번        425079 non-null  int64
 3   부번        425079 non-null  int64
 4   단지명       425079 non-null  object
 5   전용면적(㎡)   425079 non-null  float64
 6   계약년월      425079 non-null  int64
 7   계약일       425079 non-null  int64
 8   거래금액(만원)  425079 non-null  object
 9   층         425079 non-null  int64
 10  건축년도      425079 non-null  int64
 11  도로명       425079 non-null  object
 12  해제사유발생일   3417 non-null    float64
 13  거래유형      75324 non-null   object
 14  중개사소재지    75324 non-null   object
dtypes: float64(2), int64(6), object(7)
memory usage: 48.6+ MB

In [8]:
data = data.drop('해제사유발생일',axis=1)

KeyError: "['해제사유발생일'] not found in axis"

In [9]:
data = data.drop('거래유형',axis=1)
data = data.drop('중개사소재지',axis=1)
data = data.drop('도로명',axis=1)
data = data.drop('거래금액(만원)',axis=1)
data = data.drop('번지',axis=1)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 425079 entries, 0 to 425078
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   시군구      425079 non-null  object
 1   본번       425079 non-null  int64
 2   부번       425079 non-null  int64
 3   단지명      425079 non-null  object
 4   전용면적(㎡)  425079 non-null  float64
 5   계약년월     425079 non-null  int64
 6   계약일      425079 non-null  int64
 7   층        425079 non-null  int64
 8   건축년도     425079 non-null  int64
dtypes: float64(1), int64(6), object(2)
memory usage: 29.2+ MB